/*
 * This source file was generated by the Gradle 'init' task
 */

import XCTest
@testable import App

class GreeterTests: XCTestCase {
    public static let allTests = [
        ("testGreeting", testGreeting),
    ]

    func testGreeting() {
        XCTAssertEqual("Hello, World!", Greeter().greeting())
    }
}
